version: "2"

services:

  docker-in-docker:
    image: zhusj/dind:202209090250
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
    expose:
      - 2375
      - 2376

  test-runner-3:
    links:
      - docker-in-docker
    build:
      context: docker
      dockerfile: Dockerfile
      args:
        RUNNER_NAME: test-runner-3
        RUNNER_LABEL: linux.2xlarge
        RUNNER_REPO_URL: https://github.com/seemethere/test-repo
        RUNNER_TOKEN: ${RUNNER_TOKEN}
    environment:
      DOCKER_HOST: tcp://docker-in-docker:2375
